import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const jost = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">

      <body 
      className= { cn("reltative h-full font-sans antialiased", jost.className) }>
        
        <main className="relative flex flex-col min-h-screen"> {/* classname para paginas responsivas */}
        
        <Navbar/>
        <div className="flex-grow flex-1">{children}</div>

        </main>

      </body>

    </html>
  );
}
